#        _                        _            ___  _  _
#   __ _| | _____  _____ ___   __| | ___ _ __ / _ \| || |
#  / _` | |/ _ \ \/ / __/ _ \ / _` |/ _ \ '__| | | | || |_
# | (_| | |  __/>  < (_| (_) | (_| |  __/ |  | |_| |__   _|
#  \__,_|_|\___/_/\_\___\___/ \__,_|\___|_|   \___/   |_|
#
# Copyright (c) 2021 alexcoder04 <https://github.com/alexcoder04>
#
# starship (shell prompt) config file

add_newline = false
format = """[\\[ $username[@](red)$hostname$localip \\]](blue) in $directory$git_status$git_branch using \\[ $shell${custom.linux}$python$golang$nodejs\\] $jobs
${custom.chroot}${custom.lf_level}$character"""
right_format = "$cmd_duration $time"

continuation_prompt = "[+STARSHIP_CONTINUATION+ ](blue)"

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
style = "yellow"
format =  "[$hostname]($style)"
disabled = false

[directory]
truncation_length = 5
truncation_symbol = "…/"
style = "bold cyan"
read_only_style = "red bold"
read_only = "+STARSHIP_READ_ONLY+"
home_symbol = "+STARSHIP_HOME+"
format = "\\[ [$path]($style) [$read_only]($read_only_style)\\]"

[git_status]
format = " [git](blue):\\[$ahead_behind $staged$untracked$modified$renamed$deleted$conflicted$stashed\\]"
ahead = "[A](yellow)"
behind = "[B](red)"
diverged = "[D](red)"
up_to_date = "[+STARSHIP_GIT_OK+](green)"
conflicted = "[=](red)"
untracked = "[?](red)"
stashed = "$"
modified = "[!](red)"
staged = "[+](cyan)"
renamed = "[>](red)"
deleted = "[x](red)"

[git_branch]
style = "yellow"
symbol = "+STARSHIP_GIT_BRANCH+"
format = " on [$symbol$branch]($style)"

[jobs]
format = "\\[ [$symbol$number]($style) \\]"
symbol = "+STARSHIP_JOBS+"
style = "purple bold"
number_threshold = 1

[character]
success_symbol = " [+STARSHIP_SUCCESS+](bold green)"
error_symbol = " [+STARSHIP_ERROR+](bold red)"
vicmd_symbol = " [+STARSHIP_VI+](bold blue)"

[cmd_duration]
format = "\\[[$duration]($style)\\]"

[time]
disabled = false
format = "\\[[$time]($style)\\]"
style = "yellow"
time_format = "%a, %d %b %H:%M"

[localip]
format = "/[$localipv4]($style)"

[shell]
format = "[$indicator]($style) "
style = "white"
disabled = false
bash_indicator = "+STARSHIP_SHELL_BASH+"
fish_indicator = "+STARSHIP_SHELL_FISH+"
zsh_indicator = "+STARSHIP_SHELL_ZSH+"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[golang]
format = "[$symbol($version )]($style)"

[nodejs]
format = "[$symbol($version )]($style)"

[custom.lf_level]
command = "[ $LF_LEVEL = 1 ] && echo lf || echo lf$LF_LEVEL"
when = "[ ! -z $LF_LEVEL ]"
style = "bg:cyan fg:black"
format = " \\[ [$output]($style) \\]"

[custom.chroot]
command = "echo chroot"
when = "ischroot"
style = "bg:blue fg:black"
format = "\\[ [$output]($style) \\]"

[custom.linux]
command = "uname -r | cut -d- -f1"
format = "[+STARSHIP_LINUX+v$output]($style) "
style = "purple bold"
when = "true"
os = "linux"

