#!/bin/sh
#        _                        _            ___  _  _   
#   __ _| | _____  _____ ___   __| | ___ _ __ / _ \| || |  
#  / _` | |/ _ \ \/ / __/ _ \ / _` |/ _ \ '__| | | | || |_ 
# | (_| | |  __/>  < (_| (_) | (_| |  __/ |  | |_| |__   _|
#  \__,_|_|\___/_/\_\___\___/ \__,_|\___|_|   \___/   |_|  
# 
# Copyright (c) 2021 alexcoder04 <https://github.com/alexcoder04>
# 
# start X server with sx - config file
# 

export XDG_SESSION_TYPE="x11"

xrdb -load "$XDG_CONFIG_HOME/X11/Xresources"

if [ -z "$WINDOW_MANAGER" ]; then
  exec i3
fi

case "$WINDOW_MANAGER" in
  qtile*) export XDG_CURRENT_DESKTOP="qtile" ;;
esac
exec $WINDOW_MANAGER

